---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hackinh8/public_html/drupal.fossnoobs.com/themes/custom/fossnoobs

    - echo "Starting deployment process..."

    # Pull the latest changes from the GitHub repository
    - /usr/local/cpanel/3rdparty/bin/git pull origin main

    # Synchronize the GitHub repository's files with your Drupal theme directory
    - rsync -avz --delete $GIT_WORK_TREE/ $DEPLOYPATH/

    # Set the appropriate permissions for the files
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;

    - echo "Deployment completed successfully."
