---
deployment:
  tasks:
    - export DEPLOYPATH=/home/your_cpanel_username/public_html/themes/custom/fossnoobs
    - echo "Starting deployment process..." 
    # Create the target directory if it doesn't exist
    - mkdir -p $DEPLOYPATH
    # Synchronize the GitHub repository's fossnoobs folder with the target directory
    - rsync -avz --delete fossnoobs/ $DEPLOYPATH/ 
    # Set the appropriate permissions for the files and directories
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \; 
    - echo "Deployment completed successfully. Checking"